spring:
  config:
    import: optional:classpath:.env[.properties]

  datasource:
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PW}
    url: ${DATABASE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
